force-app/main/default/objects/BypassAutomation__c/BypassAutomation__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Bypass automations such as Triggers, Flows, Validation Rules</description>
    <label>Bypass Automation</label>
</CustomObject>

force-app/main/default/objects/BypassAutomation__c/fields/Accounts__c.field-meta.xml
<CustomField>
    <fullName>Accounts__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Bypass Account automations</description>
    <inlineHelpText>Bypass Account automations</inlineHelpText>
    <label>Accounts</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHandler.cls
public with sharing class AccountTriggerHandler extends TriggerHandler {
    public override Boolean isDisabled() {
        return BypassAutomation__c.getInstance().Accounts__c;
    }

    public override void applyDefaults() {
        for(Account acc: (List<Account>) Trigger.New) {
            if(String.isBlank(acc.Description)) {
                acc.Description = 'New Account';
            }
        }
    }

    public override void validate() {
        for(Account acc: (List<Account>) Trigger.New) {
            if(acc.BillingStreet == null) {
                acc.BillingStreet.addError('Address is required for new accounts.');
            }
        }
    }

    public override void beforeInsert() {
        AccountHelper.setSLA((List<Account>) Trigger.New);
    }

    public override void beforeUpdate() {
        AccountHelper.setSLA((List<Account>) Trigger.New);
    }
}